### PR TITLE
Parallelize installation

### PR DESCRIPTION
**Pull request by fatboychummy**
You don't actually need to wait for one file to download to move onto the next, you can make requests for all files at once.

I believe it may be possible for it to fail on larger repos, in that case it'll be most likely due to ratelimiting. Adding a timer to the http failure part to wait a bit and try again may be worth it in that case. I've never run into this issue personally though.

### CODE REVIEW

**Comment by tomodachi94** [comment]
Woah, this looks really good!

I was trying to dogfood `unicornpkg` to install `libunicornpkg` along with the CLI tools; you can see my attempt in `install-beta.lua`. I gave up on the ordeal.

**Comment by fatboychummy** [comment]
The few things I'm not sure about is what your variable naming conventions and whatnot are, and if you want the installer to throw an error or just "soft-error" when it fails to download the file.

Once I get those set I can mark this ready for review.

**Comment by tomodachi94** [comment]
If you could take care of those, that would be great. If you can't, I could probably tackle it on Saturday.

> your variable naming conventions

I *try* to use camelCase for everything, but sometimes I forget and use snake_case. 

> ...[and if the] installer [should] throw an error or just "soft-error" when it fails to download the file

Ideally, it should retry the request unless the error is a 404.

**Comment by fatboychummy** [comment]
Okay, I am unable to test it fully currently due to not having a proper environment set up, but I believe it should be fine. I'm marking this ready for review, but you may wish to perform your own tests as well.

**Comment by tomodachi94** [comment]
This is made obsolete by the new system.

**Pull request closed without merging**
